apiVersion: v1
kind: Secret
metadata:
    name: mysqlcreds
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:5lNK3A==,iv:RhSWE+XFFlOQIdU7v4wAv6NxeOhznohzrcBSO/LQBts=,tag:g5oRMEEPkHcWUchXmVgxJg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:v7NOlfA=,iv:EJjkqA16+kcKNJqzhEO5mM94vyO9F+dibF9pUWhPxKs=,tag:r1YFj2wEOtPwYzjLj/MKhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-26T18:21:52Z"
    mac: ENC[AES256_GCM,data:XRtwe8iM8YxVcXK0wFZ+gXjHDVgk6N57oN7locXrmC0a+ydzNkC26faXmoBpKTie77EzBp73lzxA2f/Qxg46QodraNF5/ZtiT+R/ZklM5B/PbRFRF4Tb5B3LZuJ9+UfZjs/RFslO0jvf7CeLNYOsSQidkxlGcpYZHseatyXAomY=,iv:d9HrZC49ZJMNwPIpTaFeliE/SHIvLPRE23lkjhg7TeM=,tag:8spOLc8+ft4dPCMuuRWFcA==,type:str]
    pgp:
        - created_at: "2022-10-26T18:20:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA9mgc6lCc+9yAQf/e/WLRIuoFdv7rWJq6Rnx4DDoaK4kuzJYpuDEkZ3x8gLN
            Ifs5g6UeB6PpXv2PTn76HhtaS9wfWYUlB7M52MQOu+OD08CPzP8fT9IrKNPXERHu
            5wqt0KzrYLkGRmNEYTMLo53o8aZhGHlkm+HLGxwy4FdxNzotgkU+B8mJ6GsY6H/o
            /lnoa7UhxfJLNCQoU5pAvbsAOFxO0G0Zflqly3eQNs+6AftrDggWNyEV2wBp6x4h
            GicqaOdj0aXFs9BcOCoThVYKqGgrVeTctm6zfeElEeYv8Tt2bZyQWC1rtcDJMH/Z
            +cduHFnZ5zSiYOLK7oHIQxJbGQ4Z2QcBX+5l9tuFJNJeAQqo2i+BtwoICOmkXmaa
            T91ZSHxCFpwsgnIMlOJfR2/2Lm1HKI6SNYWuDFG7yIQ6wMypUsjU+AjeE6ZcP8GZ
            76kEZ8ve9ycGcWWO0kl65zSIGyjoMkxMZ5QEVuI52w==
            =sGUe
            -----END PGP MESSAGE-----
          fp: 44E2B26E08869197A330ECA5EF5ADE747BC1F997
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
